### ISSUE TITLE
getting log.critical is not a function

### ISSUE THREAD

**Issue by mergingseas** [Rapidfacture/mongoose-multi#7]
log.critical('tried extract schemas, please Check your Schema folder, an error occured: ' + error);
             ^

TypeError: log.critical is not a function
    at Object.module.exports.start (/hassan/webapps/dizio/dizio-node/node_modules/mongoose-multi/index.js:63:14)
    at Object.<anonymous> (/hassan/webapps/dizio/dizio-node/scripts/multidbtest.js:6:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by FelixFurtmayr** [comment]
Hi mergingseas ,

this was an error in the code and should be corrected now. Please have another try with version 0.4.2.
Thanks for submitting the issue.

Regards
Felix

**Comment by mergingseas** [comment]
great thanks!
